import { AppCard, BoardPost, User } from "./types";

// 초기 관리자 계정 (실제 운영 시 환경변수로 관리)
export const INITIAL_ADMIN: Omit<User, "id" | "createdAt"> = {
  email: "admin@hitchhikers.com",
  name: "Admin",
  role: "admin",
};

// 샘플 앱 카탈로그 데이터
export const sampleApps: AppCard[] = [
  {
    id: "1",
    title: "FashionGen AI",
    thumbnail: "/placeholder-app.svg",
    description: "AI 기반 패션 디자인 생성 도구. 스타일과 트렌드를 반영한 디자인을 자동으로 생성합니다.",
    detailDescription: "FashionGen AI는 최신 생성형 AI 기술을 활용하여 패션 디자이너의 창작 과정을 혁신합니다. 트렌드 데이터와 사용자의 스타일 선호도를 분석하여 독창적인 패션 디자인을 제안합니다.",
    link: "https://example.com/fashiongen",
    industryTags: ["Fashion"],
    processTags: ["Design"],
    createdBy: "admin",
    createdAt: new Date("2025-01-15"),
    hasGeminiDemo: true,
  },
  {
    id: "2",
    title: "BagVision",
    thumbnail: "/placeholder-app.svg",
    description: "핸드백 디자인 최적화를 위한 AI 비전 솔루션.",
    detailDescription: "BagVision은 핸드백 및 가방 카테고리에 특화된 AI 비전 시스템입니다. 디자인 초안에서 최종 제품까지의 과정을 시뮬레이션하고, 시장 반응을 예측합니다.",
    link: "https://example.com/bagvision",
    industryTags: ["Bags"],
    processTags: ["Design", "Planning"],
    createdBy: "admin",
    createdAt: new Date("2025-02-10"),
  },
  {
    id: "3",
    title: "ShoeForge",
    thumbnail: "/placeholder-app.svg",
    description: "3D 신발 프로토타입 생성 AI. 제조 공정까지 자동 설계.",
    detailDescription: "ShoeForge는 3D 모델링과 AI를 결합하여 신발 프로토타입을 빠르게 생성합니다. 소재 선택부터 생산 공정 최적화까지 토탈 솔루션을 제공합니다.",
    link: "https://example.com/shoeforge",
    industryTags: ["Shoes"],
    processTags: ["Production", "Design"],
    createdBy: "admin",
    createdAt: new Date("2025-03-05"),
  },
  {
    id: "4",
    title: "BeautyTrend Analyzer",
    thumbnail: "/placeholder-app.svg",
    description: "SNS 데이터를 분석하여 뷰티 트렌드를 예측하는 AI 도구.",
    detailDescription: "BeautyTrend Analyzer는 소셜 미디어, 뷰티 블로그, 전자상거래 데이터를 실시간으로 분석하여 뷰티 트렌드를 예측합니다. 마케팅 전략 수립에 최적화된 인사이트를 제공합니다.",
    link: "https://example.com/beautytrend",
    industryTags: ["Beauty"],
    processTags: ["Planning", "Commerce"],
    createdBy: "admin",
    createdAt: new Date("2025-03-20"),
  },
  {
    id: "5",
    title: "StyleCommerce AI",
    thumbnail: "/placeholder-app.svg",
    description: "패션 이커머스를 위한 개인화 추천 엔진.",
    detailDescription: "StyleCommerce AI는 고객의 취향, 구매 이력, 트렌드 분석을 통합하여 초개인화된 패션 아이템 추천을 제공합니다. 전환율과 고객 만족도를 동시에 높입니다.",
    link: "https://example.com/stylecommerce",
    industryTags: ["Fashion", "Beauty"],
    processTags: ["Commerce"],
    createdBy: "admin",
    createdAt: new Date("2025-04-01"),
    hasGeminiDemo: true,
  },
  {
    id: "6",
    title: "FabricMind",
    thumbnail: "/placeholder-app.svg",
    description: "AI 기반 패브릭 분석 및 소재 추천 시스템.",
    detailDescription: "FabricMind는 이미지 분석과 물성 데이터를 결합하여 최적의 패브릭을 추천합니다. 지속 가능한 소재 정보와 공급업체 연결 기능을 제공합니다.",
    link: "https://example.com/fabricmind",
    industryTags: ["Fashion", "Bags", "Shoes"],
    processTags: ["Production", "Planning"],
    createdBy: "admin",
    createdAt: new Date("2025-04-05"),
  },
];

export const samplePosts: BoardPost[] = [
  {
    id: "1",
    type: "notice",
    title: "Hitchhiker's Guide to Fashion AI에 오신 것을 환영합니다!",
    content: "패션과 AI의 교차점에서 새로운 가치를 만들어가는 커뮤니티에 오신 것을 환영합니다. 다양한 AI 도구를 탐색하고, 전문가들과 의견을 나누어 보세요.",
    authorId: "admin",
    authorName: "Admin",
    isPinned: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    commentCount: 12,
  },
  {
    id: "2",
    type: "forum",
    title: "패션 디자인에서 Generative AI 활용 방법론 토론",
    content: "최근 Generative AI를 활용한 패션 디자인 사례가 늘고 있습니다. 여러분의 경험을 공유해주세요.",
    authorId: "user1",
    authorName: "DesignerKim",
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-03-15"),
    commentCount: 8,
  },
  {
    id: "3",
    type: "job",
    title: "[채용] 패션 테크 스타트업 AI 엔지니어 채용",
    content: "패션과 AI를 결합한 혁신적인 프로덕트를 만들 AI 엔지니어를 찾습니다. ML/DL 경험 3년 이상.",
    authorId: "user2",
    authorName: "FashionTechCo",
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
    commentCount: 3,
  },
  {
    id: "4",
    type: "article",
    title: "2025 패션 AI 트렌드 리포트: 생성형 AI가 바꾸는 패션의 미래",
    content: "2025년 패션 산업에서 AI 기술은 단순한 보조 도구를 넘어 창작의 핵심 파트너로 진화하고 있습니다...",
    authorId: "manager1",
    authorName: "EditorPark",
    createdAt: new Date("2025-03-28"),
    updatedAt: new Date("2025-03-28"),
    commentCount: 15,
  },
];
